### PR TITLE
`<<Video ..., auto=true>>` to auto-play inline video (GIF style)

### PR DESCRIPTION
**Pull request by aljungberg**
- Using the `="true"` work-around as in #430.
- The change in `sanitization.rb` further addresses gollum/gollum#1587 by allowing more of the standard video properties.
- Also featured: less escaping, capitalisation fix.

### CODE REVIEW

**Comment by dometto** [comment]
Thanks again! Sadly it looks like the JRuby tests fail because the markdown parser on JRuby generates `<p>` tags around the video tag. I think this is nothing to worry about, you could just make the expectation regex more lenient.

**Comment by aljungberg** [comment]
Hmm I’m not sure, isn’t the regex a find rather than a match? It feels like the first test should have failed the same way if extra `<p>`s were the problem, but it seems only the second test is failing. Also looking for that space to `%20` escape and I’m not seeing that in the actual output, instead the space seems to have been silently swallowed. Something different about how JRuby parses the macro tag such that spaces in filenames get eaten?

```
</<video (.*)src="\/Uploads\/foo%20.mp4"(.*)>(.*)<\/video>/> was expected to be =~
[17](https://github.com/gollum/gollum-lib/actions/runs/4436685631/jobs/7788167501?pr=442#step:6:18)
  <"<p><video autoplay=\"true\" height=\"100%\" loop=\"true\" muted=\"true\" playsinline=\"true\" src=\"/Uploads/foo .mp4\" width=\"100%\">HTML5 video is not supported on this browser.</video></p>\n">.
```

**Comment by dometto** [comment]
Ah, you're right about the location of the problem! It seems that `CGI.escapeHTML` does not convert spaces to `%20` on either JRuby or MRI. So the `%20` on MRI must be getting produced somewhere else in gollum, probably due to a difference in the rendering gems between MRI./JRuby. Maybe we can just change the example filename to test escaping, e.g. to something like `/Uploads/file<script>.mp4`? 

```ruby
jruby-9.4.0.0 :004 > CGI.escapeHTML("/Uploads/file<script>.mp4")
 => "/Uploads/file&lt;script&gt;.mp4" 
```

**Comment by aljungberg** [comment]
Yep works for me! Pushed.

**Comment by dometto** [comment]
Thanks for your effort!

**Pull request merged**
