### PR TITLE
First push towards a more standardized style.

### PR DESCRIPTION
**Pull request by bartkamphorst**

### CODE REVIEW

**Comment by dometto** [comment]
:+1: good work!

**Comment by dometto** [comment]
Also, maybe its worth typing up a quick style guide for future contributions? Even if it's just a couple of examples taken from this diff.

**Comment by bartkamphorst** [comment]
I've just been loosely basing myself on the unofficial [Ruby styleguide](https://github.com/bbatsov/ruby-style-guide).

**Comment by bartkamphorst** [comment]
(Hmm, looks like this failure of "test_cannot_revert_conflicting_commit" on JRuby was not introduced by my changes here, but by the latest RJGit version.)

**Comment by dometto** [comment]
> I've just been loosely basing myself on the unofficial Ruby styleguide.

:+1: After merging this, let's include a line in the Readme directing to contributors to that guide.

**Pull request merged**
