### PR TITLE
update and try pass jruby test

### PR DESCRIPTION
**Pull request by greatbody**
update and try pass jruby test

### CODE REVIEW

**Comment by dometto** [comment]
Thanks for the PR. However, the jruby errors on travis do not seem related to encoding issues, but rather to bundler/gemspec failures -- or is there an additional issue you were trying to address with this? If so, please let me know, and I'll reopen this!

**Comment by greatbody** [comment]
Hi, long time since last commit.
I created this PR to solve a problem that affects Chinese uses.
At the time I created this PR, gollum cannot let use create files using Chinese,and would transfer Chinese To English charactors.

In my PR, I make it possible to create markdown with Chinese title.
I believe Japenese can do that too if my PR was merged.

Thanks!

**Comment by bartkamphorst** [comment]
@greatbody Thanks for the PR, but we want to tackle UTF-8 encoding in a more robust way in gollum version `5.X`. Keep an eye out for that release; it should allow Chinese page names without transliteration.

**Comment by greatbody** [comment]
@bartkamphorst Thanks for your reply, I will be watching.

**Pull request closed without merging**
