### PR TITLE
Improves efficiency of subpage lookup.

### PR DESCRIPTION
**Pull request by bartkamphorst**
@dometto @jhominal I'm open to suggestions for further improvements!

### CODE REVIEW

**Comment by dometto** [comment]
I get that it's better to look for all the subpage types in one go, but ideally, we would not need to loop through (or even generate) the entire tree map -- just the trees underlying the current path. That would probably require some changes to `Wiki#tree_map_for` (or a new helper method), but I wonder whether that wouldn't be worth the effort, if we're rewriting this method anyway?

(Or maybe I'm not getting the logic and the entire treemap is not being looped through?)

**Comment by dometto** [comment]
Otherwise clean code, btw! Have you tried any benchmarks?

**Comment by bartkamphorst** [comment]
> Have you tried any benchmarks?

It roughly shaves off one second or so. Not a great improvement, but still.

**Comment by bartkamphorst** [comment]
> ideally, we would not need to loop through (or even generate) the entire tree map -- just the trees underlying the current path.

You got the logic right, and yes, I can see how this might improve things further. Suggestions for improving `Wiki#tree_map_for`?

**Comment by dometto** [comment]
I was thinking of an optional `path` argument, which on the lower level should then trigger an `ls_tree` for that path rather than for the entire repo.

**Comment by dometto** [comment]
I just realized that this of course won't improve things for pages in the root of the repository. If subpage lookup for pages in the root turns out to be a major performance impediment, we should maybe think about requiring the user to either put the subpages in the same directory as the page, or in a `subpage` directory in the same directory as the page.

**Comment by bartkamphorst** [comment]
@dometto Shall we just merge this?

**Comment by dometto** [comment]
Sorry, missed your ping there. Yeah, just merge it. :)

**Comment by bartkamphorst** [comment]
👍

**Pull request merged**
