### PR TITLE
Fix for #1004.

### PR DESCRIPTION
**Pull request by bartkamphorst**
This PR improves the code regex for org files so that it can handle handle \r\n line endings. In addition, it adds the proper indentation level to the inserted placeholder for correct rendering.

### CODE REVIEW

**Comment by bartkamphorst** [comment]
> Do we need to update other code block regexes in a similar way, or is the \r thing somehow specific to org?

Markdown and Gollum's own code blocks already deal with \r in the right way. Only the `asciidoc` code block might need some tweaking. Will investigate.

**Comment by bartkamphorst** [comment]
> Only the asciidoc code block might need some tweaking. Will investigate.

This actually relates to the question of whether [gollum should leave the code block alone](https://github.com/gollum/gollum-lib/issues/169). @dometto Any more thoughts on that issue?

**Comment by dometto** [comment]
I actually think it may be alright to do things the current way, to have CSS generation in our own hands. There are other ways to achieve what the original poster of the issue wants. What do you think?

**Comment by bartkamphorst** [comment]
I'm leaning the same way. 👍

**Comment by bartkamphorst** [comment]
> Only the asciidoc code block might need some tweaking

Looking through the [Asciidoc User Manual](https://asciidoctor.org/docs/user-manual/) Asciidoc does not seem to support nested code blocks. And if I do pass one to `asciidoctor` it also does not treat it as a code block:
```
2.4.1 :007 > contents = ::File.open('~/Desktop/asciidemo.txt', 'r').read
 => "1. Using the [[./demo_resources][resources]] listing pick a machine on which to run your demo (lets say Machine M, and Demo Ksplice)\n1. Log into that machine (Machine M)\n1. Clone the demo from the repository\n  [source,sh]\n  ----\n  git clone git@ca-ovsx32.us.oracle.com:Denver-lab/KSpliceDemo.git\n  ----\n1. =cd= to the demo directory\n  [source,sh]\n  ----\n  cd KSpliceDemo\n  ----" 
2.4.1 :008 > Asciidoctor.convert contents, safe: :safe
asciidoctor: WARNING: <stdin>: line 2: list item index: expected 2, got 1
asciidoctor: WARNING: <stdin>: line 3: list item index: expected 3, got 1
asciidoctor: WARNING: <stdin>: line 8: list item index: expected 4, got 1
 => "<div class=\"olist arabic\">\n<ol class=\"arabic\">\n<li>\n<p>Using the [[./demo_resources][resources]] listing pick a machine on which to run your demo (lets say Machine M, and Demo Ksplice)</p>\n</li>\n<li>\n<p>Log into that machine (Machine M)</p>\n</li>\n<li>\n<p>Clone the demo from the repository\n[source,sh]\n----\ngit clone <a href=\"mailto:git@ca-ovsx32.us.oracle.com\">git@ca-ovsx32.us.oracle.com</a>:Denver-lab/KSpliceDemo.git\n----</p>\n</li>\n<li>\n<p>=cd= to the demo directory\n[source,sh]\n----\ncd KSpliceDemo\n----</p>\n</li>\n</ol>\n</div>" 
```

So it would seem that this issue is not relevant for asciidoctor. Okay to merge this PR as is then?

**Comment by dometto** [comment]
👍

**Pull request merged**
