### PR TITLE
Check wiki format availability

### PR DESCRIPTION
**Pull request by ProgramFan**
This commit adds functionality to check availability of wiki formats. This information can be used by gollum/gollum#1173 to visually signal the availability of wiki formats and fix gollum/gollum#705.

### CODE REVIEW

**Comment by ProgramFan** [comment]
This is an redo of #251.

**Comment by dometto** [comment]
Great stuff. Will merge ASAP, but perhaps can you still squash this commit into logical chunks, or just into one commit? (With `git rebase -i HEAD~9`, in this case)

**Comment by ProgramFan** [comment]
Done.

**Comment by dometto** [comment]
🎆 Thanks!

**Comment by bartkamphorst** [comment]
Terrific! 🎆 🎉 👍

**Pull request merged**
