### PR TITLE
[WIP] Goodbye Grit!

### PR DESCRIPTION
**Pull request by dometto**
This PR so far:
* Refactors the revert method (see [here](https://github.com/gollum/rugged_adapter/pull/33))
* Reactivates revert tests

Todo:
- [x] Wait until new rugged adapter release
- [x] Require the new version of rugged adapter / cleanup Gemfile
- [x] Reactive revert tests
- [x] Make sure the RJGit adapter also supports the new revert method
- [x] Remove the RJGit adapter reference in Gemfile, require the right version of it in `gemspec_java.rb`.
- [x] Set rugged as default adapter
- [x] Remove all references to grit

### CODE REVIEW

**Comment by dometto** [comment]
The tests currently fail because they are being run with the grit adapter.

@bartkamphorst I won't have time to work on this for a bit. If you have any time and want to get started on a `Git#revert` method for the RJGit adapter, that would be great! (See [here](https://github.com/gollum/rugged_adapter/pull/33). It should return a `String` sha of the newly modified tree (after reverting) and an array of affected filepaths.)

**Comment by dometto** [comment]
Rugged `v0.99` has been released, which includes the required `Repo#apply` method! 🎈 🎆 🎉 🚀 🕺

**Comment by bartkamphorst** [comment]
Major step towards a 5.x release!

**Comment by dometto** [comment]
Only Jruby revert tests are failing, as expected until we release a new version of the rjgit adapter with revert support.

**Comment by dometto** [comment]
This PR should be ready to go once we merge https://github.com/gollum/rjgit_adapter/pull/14

**Pull request merged**
