### PR TITLE
Gollum lib for "verbose search"

### PR DESCRIPTION
**Pull request by C-Abner**
A new feature like gitit's search feature.

### CODE REVIEW

**Comment by dometto** [comment]
Thanks for the PR! I'll need a while to review this, please be patient. :)

**Comment by dometto** [comment]
Actually, does this already contain the actual commits...?

**Comment by C-Abner** [comment]
hi Dawa Ometto :
thank you so much for your reply.
yes, i got changed something and uploaded that commits at gollum-lib gollum
and grit-adapter

2017-10-11 19:43 GMT+08:00 Dawa Ometto <notifications@github.com>:

**Comment by dometto** [comment]
Sorry but I'm not seeing any commits other than the merge commits. :)

**Comment by bartkamphorst** [comment]
@C-Abner Am I right to think that https://github.com/gollum/gollum-lib/pull/287 is the real PR for this feature and that this PR can be closed?

**Comment by C-Abner** [comment]
@bartkamphorst  yes, this is a wrong PR . please close this. thank you a lot.

**Pull request closed without merging**
