### PR TITLE
Add allow_style config to use style attributes in HTML tags

### PR DESCRIPTION
**Pull request by svoop**
see https://github.com/gollum/gollum/issues/1127

### CODE REVIEW

**Comment by svoop** [comment]
Anything more I can do to get this PR merged?

**Comment by bartkamphorst** [comment]
Can you use [this strategy](https://github.com/gollum/gollum/wiki/Security#customization) instead for adding `style` to the attributes?

**Comment by svoop** [comment]
Ah, didn't see this one. Well, if `sanitizer.attributes[:all].push('style')` works, there's obviously no need for this PR. Closing...

**Comment by bartkamphorst** [comment]
I'd try it first, but I think it should work, yes.

**Comment by svoop** [comment]
It totally works :+1:

**Pull request closed without merging**
