### PR TITLE
Refactor Markup class

### PR DESCRIPTION
**Pull request by dometto**
* Moved the cleanup of empty `<p></p>` tags to the `Sanitize` filter, which was actually causing them to be introduced.
* Removed mysterious line

Todo:
* what's with the empty caching methods, `#update_cache` and `#check_cache`?
* can we make the complicated `class << self` block at the top more readable? I find it a bit of an odd way to handle the definition of class methods.
* The `#find_files` method should be removed, but this will require some modifications to the tag filter.

Any further suggestions welcome!

### CODE REVIEW

**Comment by bartkamphorst** [comment]
> what's with the empty caching methods, #update_cache and #check_cache?

It defines an interface. It's called in the code filter. Was probably implemented elsewhere in Github's production code to connect it to a nosql store or something. I'd keep it in.

**Comment by bartkamphorst** [comment]
> Removed mysterious line

There used to be [MarkupGFM class](https://gitlab.com/gitlab-org/gollum-lib/commit/0cc4c9f2c299ed8dc75d13fbe3c7b67f3fb7940c) (a subclass of `Markup`), and this line was [kept for compatibility](https://gitlab.com/gitlab-org/gollum-lib/commit/b5a2a8df67e7b5b74469d5a55b4e33cc745061e9). I think it is okay to remove it in 5.x. 👍

**Comment by bartkamphorst** [comment]
> can we make the complicated class << self block at the top more readable? I find it a bit of an odd way to handle the definition of class methods.

That's actually very [idiomatic in Ruby](http://www.integralist.co.uk/posts/eigenclass.html), and I honestly prefer it to explicitly defining all class methods with `def self.methodname`.

**Comment by bartkamphorst** [comment]
> The #find_files method should be removed, but this will require some modifications to the tag filter.

Agreed. 👍

**Comment by dometto** [comment]
> That's actually very idiomatic in Ruby, and I honestly prefer it to explicitly defining all class methods with def self.methodname.

I stand corrected. :)

**Pull request merged**
